"""post_remove_parent

Revision ID: 348d904fb551
Revises: 60f88b856f6c
Create Date: 2024-01-08 18:25:22.759036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '348d904fb551'
down_revision: Union[str, None] = '60f88b856f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_parent_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_parent_id_fkey', 'post', 'post', ['parent_id'], ['id'])
    # ### end Alembic commands ###
